apiVersion: v1
kind: Service
metadata:
  name: service-firefly3
  namespace: cl16
spec:
  type: LoadBalancer
  selector:
    app: firefly3
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080