apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: cl16
type: Opaque
data:
  mysql-root-password: bGFkYW5nc2VtdXQxNg==
  mysql-user: cm9vdA==
  mysql-password: bGFkYW5nc2VtdXQxNg==