apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: cl16
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306